### ISSUE TITLE
自动化更新

### ISSUE THREAD

**Issue by yesmeck** [arvinxx/sketch-typings#17]
看起来现在类型都是手写的，手写的话首先工作量非常大，而且很难持续更新。

AppKit 的部分应该可以直接解析官方文档来生成类型（AppKit 类型感觉可以单独作为一个项目）。

Sketch 私有 API 应该可以用 https://github.com/DanielMSchmidt/objective-c-parser 从 header 文件里解析出类型信息并自动生成。

Sketch 的公开 API 也可以直接从他们文档生成 https://developer.sketch.com/reference/api

**Comment by arvinxx** [comment]
目前大部分类型是从 [Sketch.d.ts](https://github.com/pravdomil/Sketch.d.ts) 这个仓库挪过来的。
仓库里 AppKit、InternalAPI 里的类型文件基本上都是从 [Sketch-Headers](https://github.com/abynim/Sketch-Headers)  这个 header 里扒出来的。
但是这种方式的问题就是大量类型定义的重复，且缺少注释信息，有效性比较低吧，所以我没有做进一步跟进。

> AppKit 的部分应该可以直接解析官方文档来生成类型（AppKit 类型感觉可以单独作为一个项目）。

挺认同的。另外补充一下一些我知道的， Sketch 好像利用了一个叫 CocoaScript 的东西，使得 Sketch 可以利用 JS 脚本去调用 macOS 的 AppKit 里的对象和模块。如果把 Appkit 中所有的 OC 方法，全部解析成 TS 的类型定义话，再结合 CocoaScript ，说不定可以实现用 TS 完成 macOS 原生 App 的开发。（不负责地随便一说）

不过这个模块在我这边的优先级挺低的，所以没有进一步去更新，基本上是用到了然后手动补一下，顺带再发布一下这样。

**Comment by yesmeck** [comment]
https://github.com/sketch-community/cocoascript-types

把 Apple 官网的文档全扒下来了。

**Comment by arvinxx** [comment]
> https://github.com/sketch-community/cocoascript-types
> 
> 把 Apple 官网的文档全扒下来了。

赞一个

**Comment by arvinxx** [comment]
sketch-community 的组织拉我下吧~我把这个仓库也挪过去

**Comment by yesmeck** [comment]
https://github.com/pravdomil/Sketch.d.ts 发现这个脚本还能正常工作的，可以继续用这个来更新 Sketch 内部 API 的类型。

**Comment by arvinxx** [comment]
> https://github.com/pravdomil/Sketch.d.ts 发现这个脚本还能正常工作的，可以继续用这个来更新 Sketch 内部 API 的类型。

这个我记得是不是会把Appkit 的API 也生成出来？会不会不太臃肿了？

**Comment by yesmeck** [comment]
不会生成 appkit 的。

**Comment by arvinxx** [comment]
> 不会生成 appkit 的。

如果是这样的话那就很完美了👍 以后 sketch 的类型定义都可以自动更新了

**Comment by arvinxx** [comment]
@yesmeck 给我个组织的权限？我把这个仓库的名称和其他的仓库统一一下~

**Comment by yesmeck** [comment]
@arvinxx  好了
