### ISSUE TITLE
缺少部分类型定义

### ISSUE THREAD

**Issue by zhu-xiaoming** [arvinxx/sketch-typings#21]
发现缺少 https://github.com/abynim/Sketch-Headers/blob/147dbf6fe05e3f2bbae9be7f7ce43de0f488dd51/Headers/AppController.h#L175 这个方法的类型定义

**Comment by arvinxx** [comment]
这个不在 sketch-types 模块里，使用这个包：https://github.com/sketch-community/cocoascript-types
