### ISSUE TITLE
failed to install sketch-types

### ISSUE THREAD

**Issue by iamyourfatherlalala** [arvinxx/sketch-typings#29]
I tried to yarn add sketch-types --dev in my own project, but it came with the following error:
![image](https://user-images.githubusercontent.com/33261859/138585215-4cc6b202-d878-496a-907d-26d7bbb0aa33.png)
But when I tried to clone this project(which uses this package in devDependencies as well) and yarn install, it went well.
https://github.com/bukinoshita/sketch-json
I really don't know what's going on. Any idea on how to fix this?

**Comment by arvinxx** [comment]
you can try `yarn add sketch-internal-types --dev` first and then `yarn add sketch-types --dev`
